apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment2
  labels:
    tier: frontend
    app: nginx
spec:
  selector:
    matchLabels:
      env: production
  replicas: 6
  template:
    metadata:
      labels:
        env: production
    spec:
      containers:
      - name: nginx
        image: nginx