#!/bin/bash
kubectl drain node01
#ssh into node
ssh node01
#text editor into kubernetes apt repository
vim /etc/apt/sources.list.d/kubernetes.list
#Update Kubernetes version to version desired
#update node
apt update
apt-cache madison kubeadm
#install new kubeadm version
apt-get install kubeadm=1.32.0-1.1
kubeadm upgrade node
#install kubelet
apt-get install kubelet=1.32.0-1.1
systemctl daemon-reload
systemctl restart kubelet
